import type { Octokit } from '@octokit/rest';
import type { GitHubRepoMapping } from '../config.js';
import type { IssueContext, AgentResult, TriageResult, PullRequestResult } from '../types.js';
import { createFixBranch, applyDiffToBranch } from './branch.js';
import { openPullRequest } from './pull-request.js';

export interface DeliveryInput {
  issueContext: IssueContext;
  agentResult: AgentResult;
  triageResult: TriageResult;
}

export interface Delivery {
  deliver(input: DeliveryInput): Promise<PullRequestResult>;
}

export function createDelivery(octokit: Octokit, config: GitHubRepoMapping): Delivery {
  return {
    async deliver(input: DeliveryInput): Promise<PullRequestResult> {
      const { issueContext, agentResult, triageResult } = input;
      const { issue } = triageResult;

      const slug = issue.title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .slice(0, 40);

      const branch = await createFixBranch(octokit, {
        owner: config.owner,
        repo: config.repo,
        baseBranch: config.baseBranch,
        issueId: issue.id,
        slug,
      });

      await applyDiffToBranch(octokit, {
        owner: config.owner,
        repo: config.repo,
        branch,
        diff: agentResult.diff,
        commitMessage: `fix: ${issue.title.slice(0, 72)}\n\nFixes Sentry issue ${issue.id}\nGenerated by sentry-bugfix-agent`,
      });

      const pr = await openPullRequest(octokit, {
        owner: config.owner,
        repo: config.repo,
        branch,
        baseBranch: config.baseBranch,
        issueContext,
        agentResult,
        triageResult,
      });

      return { url: pr.url, number: pr.number, branch };
    },
  };
}
