import type { Octokit } from '@octokit/rest';
import type { TriageResult, AgentResult, IssueContext } from '../types.js';

export interface PullRequestOptions {
  owner: string;
  repo: string;
  branch: string;
  baseBranch: string;
  issueContext: IssueContext;
  agentResult: AgentResult;
  triageResult: TriageResult;
}

export async function openPullRequest(
  octokit: Octokit,
  options: PullRequestOptions,
): Promise<{ url: string; number: number }> {
  const { owner, repo, branch, baseBranch, issueContext, agentResult, triageResult } = options;
  const { issue, severity } = triageResult;
  const { sentryDetails } = issueContext;

  const body = buildPrBody({
    issue: {
      id: issue.id,
      title: issue.title,
      permalink: issue.permalink,
      firstSeen: issue.firstSeen,
      lastSeen: issue.lastSeen,
    },
    severity,
    eventCount24h: sentryDetails.eventCount24h,
    explanation: agentResult.explanation,
    testAdded: agentResult.testAdded,
    auditLogId: agentResult.auditLogId,
  });

  const title = `fix: ${issue.title.slice(0, 60)} [sentry-${issue.id}]`;

  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title,
    body,
    head: branch,
    base: baseBranch,
    draft: false,
  });

  // Add label — create it if it doesn't exist
  await ensureLabel(octokit, { owner, repo });
  await octokit.issues.addLabels({
    owner,
    repo,
    issue_number: pr.number,
    labels: ['agent-fix'],
  });

  return { url: pr.html_url, number: pr.number };
}

async function ensureLabel(
  octokit: Octokit,
  options: { owner: string; repo: string },
): Promise<void> {
  try {
    await octokit.issues.getLabel({
      owner: options.owner,
      repo: options.repo,
      name: 'agent-fix',
    });
  } catch {
    await octokit.issues.createLabel({
      owner: options.owner,
      repo: options.repo,
      name: 'agent-fix',
      color: '0075ca',
      description: 'Automatically generated fix from sentry-bugfix-agent',
    });
  }
}

interface PrBodyOptions {
  issue: {
    id: string;
    title: string;
    permalink: string;
    firstSeen: string;
    lastSeen: string;
  };
  severity: string;
  eventCount24h: number;
  explanation: string;
  testAdded: boolean;
  auditLogId: string;
}

function buildPrBody(opts: PrBodyOptions): string {
  const severityEmoji: Record<string, string> = {
    minor: '🟡',
    major: '🟠',
    critical: '🔴',
  };
  const emoji = severityEmoji[opts.severity] ?? '⚪';

  return `## Agent-Generated Bug Fix

> ⚠️ **This PR was created by an automated agent. It requires human review before merging.**
> The agent never merges — all merges are performed by humans.

### Sentry Issue

| Field | Value |
|-------|-------|
| Issue ID | \`${opts.issue.id}\` |
| Severity | ${emoji} ${opts.severity} |
| Title | ${opts.issue.title} |
| First seen | ${opts.issue.firstSeen} |
| Last seen | ${opts.issue.lastSeen} |
| Events (24h) | ${opts.eventCount24h} |
| Sentry link | ${opts.issue.permalink ? `[View in Sentry](${opts.issue.permalink})` : 'N/A'} |

---

### Root Cause & Fix

${opts.explanation || '_The agent did not provide a detailed explanation._'}

---

### Review Checklist

Before merging, please verify:

- [ ] The root cause explanation matches your understanding of the bug
- [ ] The fix is minimal and does not introduce unrelated changes
- [ ] ${opts.testAdded ? 'The new test correctly exercises the fixed code path' : 'A test covers the fixed code path (the agent did not add one)'}
- [ ] No new external dependencies were introduced
- [ ] CI passes on this branch

---

### Audit Trail

Audit log entry ID: \`${opts.auditLogId}\`

All agent actions (prompts, tool calls, model responses) are recorded in the pipeline's JSONL audit log. Contact the pipeline operator to retrieve the full trace for this run.

---

*Generated by [sentry-bugfix-agent](https://github.com/your-org/sentry-bugfix-agent) — an independent open-source project, not affiliated with Sentry (Functional Software, Inc.).*
`;
}
